/* PRESCRIPTION */
export const PRESCRIPTION_LIST = 'PRESCRIPTION_LIST';
export const PRESCRIPTION_LIST_SUCCESS = 'PRESCRIPTION_LIST_SUCCESS';
export const PRESCRIPTION_LIST_FAILED = 'PRESCRIPTION_LIST_FAILED';

export const PRESCRIPTION_ADD = 'PRESCRIPTION_ADD';
export const PRESCRIPTION_ADD_SUCCESS = 'PRESCRIPTION_ADD_SUCCESS';
export const PRESCRIPTION_ADD_FAILED = 'PRESCRIPTIONADD_ADD_FAILED';

export const PRESCRIPTION_UPDATE = 'PRESCRIPTION_UPDATE';
export const PRESCRIPTION_UPDATE_SUCCESS = 'PRESCRIPTION_UPDATE_SUCCESS';
export const PRESCRIPTION_UPDATE_FAILED = 'PRESCRIPTION_UPDATE_FAILED';

export const PRESCRIPTION_DELETE = 'PRESCRIPTION_DELETE';
export const PRESCRIPTION_DELETE_SUCCESS = 'PRESCRIPTION_DELETE_SUCCESS';
export const PRESCRIPTION_DELETE_FAILED = 'PRESCRIPTIONADD_DELETE_FAILED';
